### ISSUE TITLE
Instruction page if ungit is not installed

### ISSUE THREAD

**Issue by ibnesayeed** [codingtwinky/atom-ungit#18]
First of all, the README file needs to mention that for this package to work, ungit must be installed (and a link to installation instructions that are noted on the README of the main ungit repository).

Also, it will be nice if a user installs this package and does not have ungit (or even nodejs) installed then the iframe under the ungit tab of the editor should show a page with instructions to install necessary things to get it working.

**Comment by pwFoo** [comment]
I have trouble to get atom-ungit working with Windows 10. Works fine with Linux...

Tried to install
* Atom and atom-ungit (package install failed without notification)
* Atom, nodejs and atom-ungit (package installed, but not opens)
* Atom, nodejs, ungit and atom-ungit (package installed, but not opens)

So what's wrong / missing?

**Comment by codingtwinky** [comment]
Hi,

Requirement for atom-ungit is nodejs and atom.  i'm not sure what you mean by but not opens.  Could you share the client log in atomjs via opening the [developer's tool](https://developers.google.com/web/tools/chrome-devtools/iterate/inspect-styles/shortcuts?hl=en)?

**Comment by pwFoo** [comment]
I used atom-ungit @ Linux and all works fine. ungit opens up as a atom "tab", but with Windows10 ungit works only with the browser outside of atom. It's not integrated as expected.

**Comment by codingtwinky** [comment]
I understand it is functional in linux but could you possibly share the atom client log in windows 10 so I can help you debug or possibly fix?  Without it, I'm blind to what the problem is.

**Comment by pwFoo** [comment]
Today the new Surface Pro 4 stopped working after just a week... So I can't take a closer look at logs at the moment. I think it have to be replaced...

Maybe it was related to my Chrome and audio bugs I experienced... Also recovery doesn't work. Maybe my problem is Surface firmware / Win10 related...

**Comment by pwFoo** [comment]
Tested again atom-ungit (current version with up to date atom). ungit works fine standalone. 
Starting ungit as atom package (atom ui packages menu).
```
atom-ungit.coffee:121 module.js:457
    throw err;
    ^

Error: Cannot find module 'C:\Users\pwfoo'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
(anonymous function) @ atom-ungit.coffee:121emitOne @ events.js:95emit @ events.js:182readableAddChunk @ _stream_readable.js:153Readable.push @ _stream_readable.js:111onread @ net.js:531
```
