### ISSUE TITLE
Uncaught Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by benogle** [codingtwinky/atom-ungit#20]
_From @JostCrow on January 23, 2015 9:46_

[Enter steps to reproduce below:]

1. killed ungit via ctrl+p.
2. pressed ctrl+p again afterwards.
3. Nothing happened so I pressed it again.

**Atom Version**: 0.175.0
**System**: linux 3.13.0-44-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: connect ECONNREFUSED

```
At events.js:85

Error: connect ECONNREFUSED
  at exports._errnoException (util.js:746:11)
  at Object.afterConnect [as oncomplete] (net.js:990:19)

```

### Commands

```
     -0:24.2 window:run-package-specs (atom-text-editor.editor)
  3x -0:21.2 project-manager:toggle (atom-text-editor.editor)
     -0:19.5 core:move-up (atom-text-editor.editor.mini)
     -0:19.3 core:confirm (atom-text-editor.editor.mini)
     -0:16.1 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:14.3 core:confirm (atom-text-editor.editor.mini)
     -0:14.3 ungit:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:01.9 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 ungit:kill (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs",
      "tree-view",
      "linter-python-pep8",
      "toolbar",
      "toolbar-main",
      "pane-layout-plus",
      "indent-guide-improved"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 12,
    "showIndentGuide": true,
    "tabLength": 4,
    "scrollSensitivity": 80,
    "scrollPastEnd": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-python-debugger, v0.1.1
atom-ungit, v0.4.0
autoclose-html, v0.13.0
autocomplete-plus, v1.1.0
autocomplete-plus-async, v0.22.0
highlight-selected, v0.7.0
language-django, v0.1.1
linter, v0.10.1
linter-pep8, v0.1.0
minimap, v3.5.6
minimap-color-highlight, v3.1.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.0
minimap-highlight-selected, v3.1.0
minimap-selection, v3.1.1
monokai, v0.11.0
project-manager, v1.15.0
python-isort, v0.0.5
set-syntax, v0.1.0
sublime-tabs, v0.4.8
tab-history, v0.4.0

# Dev
No dev packages
```

_Copied from original issue: atom/atom#5230_

**Comment by benogle** [comment]
_From @mnquintana on January 23, 2015 12:37_

I can't reproduce this in OS X 10.10.1, Atom 0.175.0. Can you try seeing if you can reproduce this with all of your installed packages disabled except atom-ungit?

**Comment by codingtwinky** [comment]
@benogle Thanks and will be looking at it.

@JostCrow First thing I would suspect is that wether or not ungit is able to use provided port, by default ungit uses 8448.  Best thing to do is install [ungit](https://github.com/FredrikNoren/ungit) within npm and see if you can run that independently from atom-ungit.

Admittedly I do not own any windows machine so atom-ungit's window durability is spotty at best but I will see what I can do help you with this problem.

**Comment by JostCrow** [comment]
@codingtwinky I used ungit before outside of atom. I can still run ungit and use it independently.

**Comment by codingtwinky** [comment]
I'm not able to reproduce this issue and I'm not sure how to approach this.
