### ISSUE TITLE
"undefined" at Socket(atom-ungit.coffee:92:18)

### ISSUE THREAD

**Issue by ginus** [codingtwinky/atom-ungit#27]
[Enter steps to reproduce below:]

1. When start ungit package, this error displayed

**Atom Version**: 0.194.0
**System**: Unknown Windows Version
**Thrown From**: [atom-ungit](https://github.com/codingtwinky/atom-ungit) package, v0.4.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\Administrator\.atom\packages\atom-ungit\lib\atom-ungit.coffee:92

TypeError: undefined is not a function
  at Socket.<anonymous> (C:\Users\Administrator\.atom\packages\atom-ungit\lib\atom-ungit.coffee:92:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
     -2:02.4.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-monokai-seti.theme-seti-ui)
     -0:03.7.0 ungit:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-go",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "log-console",
      "language-objective-c",
      "language-mustache",
      "autocomplete",
      "jshint",
      "language-perl",
      "language-property-list",
      "emmet",
      "terminal-runner",
      "file-type-icons",
      "preview-plus",
      "atom-lint",
      "jslint",
      "atom-terminal-panel",
      "tidy-tabs"
    ],
    "projectHome": "D:\\web",
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.22
atom-ungit, v0.4.3
atomatigit, v1.3.0
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
autocomplete-snippets, v1.2.0
code-links, v0.3.8
coffee-links, v0.1.0
coffee-refactor, v0.6.2
color-picker, v1.7.0
highlight-selected, v0.9.2
js-refactor, v0.3.0
language-asp, v1.0.0
language-aspx, v0.4.0
language-batchfile, v0.4.0
language-ect, v0.2.0
language-gitignore, v0.2.0
language-livescript-edge, v1.0.0
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-htmlhint, v0.0.13
linter-jshint, v0.1.2
linter-lsc, v1.1.2
linter-php, v0.0.12
minimap, v4.7.6
mocha, v0.0.5
monokai-seti, v0.7.0
navigate, v0.0.10
project-palette-finder, v2.4.16
project-ring, v0.19.6
refactor, v0.4.1
rest-client, v0.3.1
seti-ui, v0.6.3
Stylus, v0.7.0
webbox-color, v0.5.6
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by codingtwinky** [comment]
@ginus could you try v0.5.0?

There were some atom api changes and more interestingly `ScrollView` object within core has some issues.  this was addressed via separated out `atom-space-pen-views` dependency. 

This should fix and and work with atom 0.207.0.


Sorry about the terrible delay, it has been crazy busy...
