### ISSUE TITLE
Toggle and Kill functionalities not working

### ISSUE THREAD

**Issue by ibnesayeed** [codingtwinky/atom-ungit#36]
There are several things wrong with atom-ungit in my installation on Atom 0.206.0 on Ubuntu 14.10.

- [x] Toggle command creates a new tab every time instead of killing one if exists already.
- [x] Kill command throws an error (trace added below.)
- [x] Atom-ungit style is not loading or not applied as a result:
 - there is an ugly border around the iframe and
 - tab does not show the logo, instead it shows the text "Uri-web".

Error on kill command:

```
/home/USER_NAME/.atom/packages/atom-ungit/lib/atom-ungit.coffee:55

TypeError: undefined is not a function
    at Object.module.exports.closeUngit (/home/USER_NAME/.atom/packages/atom-ungit/lib/atom-ungit.coffee:82:36)
    at Object.module.exports.kill (/home/USER_NAME/.atom/packages/atom-ungit/lib/atom-ungit.coffee:76:12)
    at atom-workspace.atom.commands.add.ungit:kill (/home/USER_NAME/.atom/packages/atom-ungit/lib/atom-ungit.coffee:57:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:238:29)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:153:19)
    at EventEmitter.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```

**Comment by codingtwinky** [comment]
I was too focus on bringing it to a workable state so those features are largely removed...  I will fix it up in next few days but feel free to send pull requests...

**Comment by ibnesayeed** [comment]
I would rather wait your implementation. Currently I am little too busy to hack into this as I am getting ready for some academic conferences in the coming weeks.

**Comment by codingtwinky** [comment]
Try latest, all should be fixed
