### ISSUE TITLE
unable to install this package

### ISSUE THREAD

**Issue by capaj** [codingtwinky/atom-ungit#39]
This is my error log.
```
> typechecker@2.0.8 preinstall /tmp/apm-install-dir-115919-14427-83m86g/node_modules/atom-ungit/node_modules/ungit/node_modules/getmac/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> ws@0.4.32 install /tmp/apm-install-dir-115919-14427-83m86g/node_modules/atom-ungit/node_modules/ungit/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


npm WARN engine forever-monitor@1.1.0: wanted: {"node":"0.8.x"} (current: {"node":"0.10.40","npm":"2.13.3"})

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-115919-14427-83m86g/node_modules/atom-ungit/node_modules/ungit/node_modules/getmac/node_modules/extract-opts/node_modules/typechecker/cyclic.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/capaj/.atom/.apm/.apmrc" "--userconfig" "/home/capaj/.atom/.apmrc" "install" "/tmp/d-115919-14427-1p7mzmw/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! typechecker@2.0.8 preinstall: `node ./cyclic.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the typechecker@2.0.8 preinstall script 'node ./cyclic.js'.
npm ERR! This is most likely a problem with the typechecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./cyclic.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls typechecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115919-14427-83m86g/npm-debug.log
```

**Comment by codingtwinky** [comment]
Hmm...   Can you try `npm install getmac@1.0.7`?  That should give you same error message, which would undoubtedly confirm that this is the issue with the dependency of one of the Ungit's dependency, getmac@1.0.7.  

What OS are you on?  if you are not troubled by `npm install typecheck@4.0.0` this could be a simpler fix for us.

**Comment by capaj** [comment]
@codingtwinky I am on Ubuntu 15.04, node 4.2.0
getmac installs fine, but `npm install typecheck@4.0.0` gives me an error-latest version of that package seems to be `0.1.2 `

**Comment by codingtwinky** [comment]
Sorry i meant `npm install typechecker@4.0.0`.  However that doesn't matter as my suspicion was that getmac@1.0.7 installation causes failure.   few questions, this is an installation failure right? not run time failure.  And do you have ungit installed separately in your machine or is this first time using ungit it general?

**Comment by capaj** [comment]
Yes, installation. When I tried to install it for the first time, I did not have ungit installed in CLI. Now I have, but the install still fails.

**Comment by codingtwinky** [comment]
I cannot replicate this issue, and it doesn't really make sense.  it complains about missing module in `.../ungit/.../getmac/.../extract-opts/.../typechecker` so getmac installation should have failed.  

When you run into it next time can you tell me the version number of ungit, getmac, and typechecker by looking up the temp folder?
